### ISSUE TITLE
Subscriptions in GraphQL

### ISSUE THREAD

**Issue by moltar** [adonisjs/adonis-websocket-protocol#2]
I think GraphQL is here to stay and arguably is the future of APIs. Thus need to make sure whatever websocket strategy Adonis picks is compatible with Subscriptions in GraphQL (even if an adapter needs to be created).

Reference implementation: https://github.com/apollographql/subscriptions-transport-ws

**Comment by rafaelfess** [comment]
Absolutely! I'm developing an application using AdonisJS with the Apollo Server GraphQL package for AdonisJS, and every query and mutation is working fine.

Now, I'm trying to implement the subscriptions. Have you had succeed implementing the subscriptions on AdonisJS, @moltar ?

**Comment by moltar** [comment]
@rafaelfesi I have not tried adding subs yet. My understanding is that Adonis team wants to have some proprietary way for WebSocket connections (which is what this repo is for - to document the approach). My understanding is that this approach is not yet production ready, and merely a living document. This is as far was Adonis 4 goes. In Adonis 3 there was native WS support.

I think subs can be achieved two ways right now:

1) Use vanilla WebSockets with pub/sub setup (e.g. via Redis). You can most likely use existing Apollo packages for this, with minimal need to amend anything in Adonis. Probably the easiest short term way.

2) Write a transport layer for Apollo that uses Adonis' WS libraries (which are outlined in the README of this repo).

**Comment by moltar** [comment]
Btw, if you want to pair on that to figure out - let me know. We can do some pair programming to solve this.
